CREATE TABLE IF NOT EXISTS USERS (
	USER_NO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	USER_NAME VARCHAR(100) NOT NULL,
	USER_EMAIL VARCHAR(255) NOT NULL,
	USER_PASSWORD VARCHAR(255) NOT NULL,
	USER_ENABLED BOOLEAN DEFAULT TRUE,
	USER_POINT INT DEFAULT 0,
	USER_UPDATED_DATE DATE,
	USER_CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE IF NOT EXISTS BOOKS (
	BOOK_NO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	BOOK_TITLE VARCHAR(255) NOT NULL,
	BOOK_AUTHOR VARCHAR(255) NOT NULL,
	BOOK_PUBLISHER VARCHAR(255) NOT NULL,
	BOOK_DESCRIPTION TEXT,
	BOOK_PRICE INT NOT NULL,
	BOOK_DISCOUNT_PRICE INT NOT NULL,
	BOOK_STOCK INT NOT NULL,
	BOOK_UPDATED_DATE DATE,
	BOOK_CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE IF NOT EXISTS CART_ITEMS (
	CART_ITEM_NO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	USER_NO INT REFERENCES USERS (USER_NO),
	BOOK_NO INT REFERENCES BOOKS (BOOK_NO),
	QUANTITY INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS (
	ORDER_ID VARCHAR(100) PRIMARY KEY,
	USER_NO INT REFERENCES USERS (USER_NO),
	ORDER_STATUS VARCHAR(100) CHECK (ORDER_STATUS IN ('결재완료', '취소', '환불신청', '환불완료', '배송중', '배송완료')),
	TOTAL_PRICE INT,
	ORDER_UPDATED_DATE DATE,
	ORDER_CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
	ORDER_ITEM_NO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	BOOK_NO INT REFERENCES BOOKS (BOOK_NO),
	QUANTITY INT NOT NULL,
	PRICE INT NOT NULL,
	ORDER_ID VARCHAR(100) REFERENCES ORDERS (ORDER_ID)
);