server:
  port: 80
  
logging:
  level:
    '[com.example.mapper]': trace

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  profiles:
    include:
    - auth
          
mybatis:
  mapper-locations:
  - mybatis/mappers/*.xml
  configuration:
    jdbc-type-for-null: 'NULL'
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

    
    
