spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "google client id"
            client-secret: "google client secret"
            scope:
            - email
            - profile
          kakao:
            client-id: "다음 REST API"
            client-secret: "다음 client secret"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope:
            - profile_nickname
            - profile_image
            - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id            

    
    
