server:
  port: 80
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
naver:
  client:
    id: xxxxxxxx          #네이버 애플리케이션 클라이언트 아이디을 입력합니다.
    secret: xxxxxxxx      #네이버 애플리케이션 클라이언트 시크릿을 입력합니다.
  captcha:
    url:
      key: https://openapi.naver.com/v1/captcha/nkey?code=0
      image: https://openapi.naver.com/v1/captcha/ncaptcha.bin
      validation: https://openapi.naver.com/v1/captcha/nkey?code=1
    
