server:
  port: 80
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
naver:
  client:
    id: 77PI9mBc0SQ6HnSgeZLm
    secret: uj0l1xgxTq
  captcha:
    url:
      key: https://openapi.naver.com/v1/captcha/nkey?code=0
      image: https://openapi.naver.com/v1/captcha/ncaptcha.bin
      validation: https://openapi.naver.com/v1/captcha/nkey?code=1
    