server:
  port: 80
  
logging:
  level:
    '[com.example.mapper]': trace
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
mybatis:
  mapper-locations:
  - mappers/*.xml
  